;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        end-of-visual-line
        evil-append
        evil-backward-word-begin
        evil-change
        evil-exit-visual-state
        evil-forward-WORD-end
        evil-forward-word-begin
        evil-forward-word-end
        evil-insert-line
        evil-next-visual-line-dwim
        evil-normal-state
        evil-previous-visual-line-dwim
        evil-visual-char
        hydra-evil-leader-multiple-cursors/mc/unmark-this
        move-beginning-of-line-dwim
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window-dwim
        evil-record-macro
        helm-M-x
        helm-confirm-and-exit-minibuffer
        hydra-evil-leader-multiple-cursors/mc/mark-next-like-this
        hydra-evil-leader-multiple-cursors/mc/mark-next-symbol-like-this
        hydra-evil-leader-multiple-cursors/mc/mark-previous-like-this
        hydra-evil-leader-multiple-cursors/mc/unmark-next-like-this
        hydra-evil-leader-multiple-cursors/mc/unmark-previous-like-this
        hydra-evil-leader-multiple-cursors/nil
        hydra-keyboard-quit
        mc/unmark-this
        ))
