#+TITLE: Starter Kit Misc
#+OPTIONS: toc:nil num:nil ^:nil

This is part of the [[file:starter-kit.org][Emacs Starter Kit]].

* Starter Kit Misc
Things that don't fit anywhere else.

** Ensure server safe in windows
On Windows and Cygwin, errors of /some/path/ is unsafe often occur. So
redefine server-ensure-safe-dir function to suppress this kind of error.
Besides, you should make "/tmp/emacs500" directory manually or server cannot
start.
#+BEGIN_SRC emacs-lisp
(when (or *win32* *cygwin*)
  (defun server-ensure-safe-dir (dir) "Noop" t)
  (unless (file-exists-p "/tmp/emacs500")
    (mkdir "/tmp/emacs500")))
(unless (server-running-p)
  (server-start))
#+END_SRC

** Diminish minor modes
   
The minor mode list is too long and occupy all the mode line. I want to know
other data on the mode line.
#+BEGIN_SRC emacs-lisp
(eval-after-load "undo-tree"             '(diminish 'undo-tree-mode))
(eval-after-load "flyspell"              '(diminish 'flyspell-mode))
(eval-after-load "auto-complete"         '(diminish 'auto-complete-mode))
(eval-after-load "eldoc"                 '(diminish 'eldoc-mode))
(eval-after-load "magit"                 '(diminish 'magit-auto-revert-mode))
(eval-after-load "smartparens"           '(diminish 'smartparens-mode))
(eval-after-load "cdlatex"               '(diminish 'org-cdlatex-mode))
(eval-after-load "outline"               '(diminish 'outline-minor-mode))
(eval-after-load "abbrev"                '(diminish 'abbrev-mode))
(eval-after-load "highlight-indentation" '(diminish 'highlight-indentation-current-column-mode))
(diminish 'hs-minor-mode)
(diminish 'auto-fill-function)
#+END_SRC

** Window systems
#+srcname: starter-kit-window-view-stuff
#+begin_src emacs-lisp 
  (when window-system
    (setq frame-title-format '(buffer-file-name "%f" ("%b")))
    (blink-cursor-mode -1)
    (when (require 'mwheel nil 'no-error) (mouse-wheel-mode t)))
  
  (set-terminal-coding-system 'utf-8)
  (set-keyboard-coding-system 'utf-8)
  (prefer-coding-system 'utf-8)
  
  (setq visible-bell t
        echo-keystrokes 0.1
        font-lock-maximum-decoration t
        inhibit-startup-message t
        transient-mark-mode t
        color-theme-is-global t
        delete-by-moving-to-trash t
        shift-select-mode nil
        truncate-partial-width-windows nil
        uniquify-buffer-name-style 'forward
        whitespace-style '(trailing lines space-before-tab
                                    indentation space-after-tab)
        whitespace-line-column 100
        ediff-window-setup-function 'ediff-setup-windows-plain
        oddmuse-directory (concat starter-kit-dir "oddmuse")
        xterm-mouse-mode t)
#+end_src
   
** Winner mode
Winner mode enables you goto previous windows configuration easily.
#+BEGIN_SRC emacs-lisp
(winner-mode 1)
#+END_SRC

** Save places in opened files

When you visit a file, point goes to the last place where it was when you
previously visited the same file.
#+BEGIN_SRC emacs-lisp
(setq-default save-place t)
(setq save-place-file (concat starter-kit-dir ".saved-places"))
(require 'saveplace)
#+END_SRC

** Transparently open compressed files
#+begin_src emacs-lisp
(auto-compression-mode t)
#+end_src

** Save a list of recent files visited.
#+begin_src emacs-lisp 
(setq recentf-max-saved-items 128)
(recentf-mode 1)
#+end_src

** ido mode
+ ido-mode is like magic pixie dust! 
+ Sometimes ido can't find a file, just run *M-x ido-reread-directory* or
  *C-l* in minibuffer to refresh ido candidates.
#+srcname: starter-kit-loves-ido-mode
#+begin_src emacs-lisp 
(ido-mode 1)
(ido-everywhere 1)
(flx-ido-mode 1)
(setq ido-enable-prefix nil
      ido-enable-flex-matching t
      ido-create-new-buffer 'always
      ido-use-filename-at-point nil
      ido-use-virtual-buffers t
      ido-auto-merge-work-directories-length -1
      ido-save-directory-list-file (concat starter-kit-dir ".ido.last")
      ido-max-prospects 10)
;; disable ido faces to see flx highlights.
(setq ido-enable-flex-matching t)
(setq ido-use-faces nil)
#+end_src

** Other, spell checking, tabs, imenu
#+begin_src emacs-lisp 
  (set-default 'indent-tabs-mode nil)
  (set-default 'indicate-empty-lines t)
  (set-default 'imenu-auto-rescan t)
  
  (add-hook 'text-mode-hook 'turn-on-auto-fill)
  (add-hook 'text-mode-hook 'turn-on-flyspell)
  
  (defalias 'yes-or-no-p 'y-or-n-p)
  ;; Seed the random-number generator
  (random t)
#+end_src

*** functions for prettier source code
#+begin_src emacs-lisp
(defun starter-kit-pretty-lambdas ()
  (font-lock-add-keywords
   nil `(("(\\(lambda\\>\\)"
          (0 (progn (compose-region (match-beginning 1) (match-end 1)
                                    ,(make-char 'greek-iso8859-7 107))
                    nil))))))
#+end_src

*** possible issues/resolutions with flyspell
Most of the solution came from [[http://www.emacswiki.org/emacs/FlySpell][EmacsWiki-FlySpell]].  Here is one
possible fix.

**** Emacs set path to aspell
it's possible aspell isn't in your path
#+begin_src emacs-lisp :tangle no
   (setq exec-path (append exec-path '("/opt/local/bin")))
#+end_src

**** Emacs specify spelling program
- This didn't work at first, possibly because cocoAspell was
  building its dictionary.  Now it seems to work fine.
#+begin_src emacs-lisp :tangle no
  (setq ispell-program-name "aspell"
        ispell-dictionary "english"
        ispell-dictionary-alist
        (let ((default '("[A-Za-z]" "[^A-Za-z]" "[']" nil
                         ("-B" "-d" "english" "--dict-dir"
                          "/Library/Application Support/cocoAspell/aspell6-en-6.0-0")
                         nil iso-8859-1)))
          `((nil ,@default)
            ("english" ,@default))))
#+end_src

** Hippie expand: at times perhaps too hip
#+begin_src emacs-lisp
  (when (boundp 'hippie-expand-try-functions-list)
    (delete 'try-expand-line hippie-expand-try-functions-list)
    (delete 'try-expand-list hippie-expand-try-functions-list))
#+end_src

** Backup files
Rather than saving backup files scattered all over the file system,
let them live in the =~/.emacs-backups/= directory.
#+begin_src emacs-lisp
(setq backup-directory-alist `(("." . ,(expand-file-name "~/.backups-emacs")))
      backup-by-copying t
      delete-old-versions t
      kept-new-versions 6
      kept-old-versions 2
      version-control t)
#+end_src

** Default to unified diffs
#+begin_src emacs-lisp
(setq diff-switches "-u")
#+end_src

** Cosmetics

#+begin_src emacs-lisp
(eval-after-load 'diff-mode
  '(progn
     (set-face-foreground 'diff-added "green4")
     (set-face-foreground 'diff-removed "red3")))

(eval-after-load 'magit
  '(progn
     (set-face-foreground 'magit-diff-add "green3")
     (set-face-foreground 'magit-diff-del "red3")))
#+end_src

** Bookmark

#+BEGIN_SRC emacs-lisp
(setq bmkp-bmenu-state-file (expand-file-name "~/.emacs.d/.emacs-bmk-bmenu-state.el"))
#+END_SRC

** Always auto revert file
#+BEGIN_SRC emacs-lisp
(global-auto-revert-mode 1)
#+END_SRC

** Enable erase buffer
#+BEGIN_SRC emacs-lisp
(put 'erase-buffer 'disabled nil)
#+END_SRC

** 80 Column Rule
It's a good habit to obey to 80 column rule. In the convenience of adding
continuation marker in code such as Fortran, two columns are spared.
#+BEGIN_SRC emacs-lisp
(setq default-fill-column 78)
#+END_SRC

** Disable recentering
   For smooth scrolling and disabling the auto-recentering of emacs screen when
moving cursor. Set scroll margin to be 4 so that an ape can see the following
lines of codes.
#+BEGIN_SRC emacs-lisp
(setq scroll-step 1
      scroll-conservatively 10000
      auto-window-vscroll nil)
(setq scroll-margin 4)
#+END_SRC

** New line and indent
#+BEGIN_SRC emacs-lisp 
(define-key global-map (kbd "RET") 'newline-and-indent)
#+END_SRC

** Undo is needed by evil
#+BEGIN_SRC emacs-lisp 
(global-undo-tree-mode)
#+END_SRC
   
** Expand region

#+BEGIN_QUOTE
Expand region increases the selected region by semantic units. Just keep
pressing the key until it selects what you want.
#+END_QUOTE
   
In terminal, *C-=* may not work. You may have to run extended-command-history
to expand or contract region.

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-=") 'er/expand-region)
#+END_SRC

** Garbage collection
   
Emacs GC is time consuming for that Emacs will initiate GC every 0.76 MB. We
set it to be 20 MB to save time.
#+BEGIN_SRC emacs-lisp 
(setq gc-cons-threshold 20000000)
#+END_SRC

** Grep

Don't grep repositories.
#+BEGIN_SRC emacs-lisp 
(eval-after-load 'grep
  '(dolist (dir '(".git"
                  ".cvs"
                  ".svn"
                  ".hg"))
     (add-to-list 'grep-find-ignored-directories dir)))
#+END_SRC

** Window numbering

Changing from one window to another is so easy in Emacs with window number,
you just key in *M-n* to jump to n-th window numbered by the plugin.
#+BEGIN_SRC emacs-lisp
(window-numbering-mode 1)
#+END_SRC

** Ediff

Recover previous windows configuration when quitting ediff.
#+BEGIN_SRC emacs-lisp
(add-hook 'ediff-after-quit-hook-internal 'winner-undo)
#+END_SRC

** Compile

Save buffers before compile automatically.
#+BEGIN_SRC emacs-lisp
(setq compilation-ask-about-save nil)
#+END_SRC

