#+TITLE: Starter Kit Shell
#+OPTIONS: toc:nil num:nil ^:nil

This is part of the [[file:starter-kit.org][Emacs Starter Kit]].

* Starter Kit Shell
  
** Eshell
[[http://www.emacswiki.org/emacs/CategoryEshell][Eshell]] is a great shell.

*** Configurations

#+begin_src emacs-lisp
  (setq eshell-cmpl-cycle-completions nil
        eshell-save-history-on-exit t
        eshell-cmpl-dir-ignore "\\`\\(\\.\\.?\\|CVS\\|\\.svn\\|\\.git\\)/\\'")
  
  (eval-after-load 'esh-opt
    '(progn
       ;; TODO: for some reason requiring this here breaks it, but
       ;; requiring it after an eshell session is started works fine.
       ;; (require 'eshell-vc)
       (setenv "PAGER" "cat")
       ; (set-face-attribute 'eshell-prompt nil :foreground "turquoise1")
       (add-hook 'eshell-mode-hook ;; for some reason this needs to be a hook
                 '(lambda () (define-key eshell-mode-map "\C-a" 'eshell-bol)))
       (add-to-list 'eshell-visual-commands "ssh")
       (add-to-list 'eshell-visual-commands "tail")
       (add-to-list 'eshell-command-completions-alist
                    '("gunzip" "gz\\'"))
       (add-to-list 'eshell-command-completions-alist
                    '("tar" "\\(\\.tar|\\.tgz\\|\\.tar\\.gz\\)\\'"))
       ;; (add-to-list 'eshell-output-filter-functions 'eshell-handle-ansi-color)
       ))
#+end_src

The =eshell= directory holds alias definitions and history
information.  It is much like a =.bashrc= file for those who are
familiar with bash.  This set the value of =eshell-directory-name= to
point to the =eshell= directory in this directory.  The =alias= file
is pre-populated with some generally applicable aliases.

#+begin_src emacs-lisp
  (setq eshell-directory-name
        (expand-file-name "./" (expand-file-name "eshell" starter-kit-dir)))
#+end_src

*** Multiple eshells
You can create eshell by just *M-x eshell*, or if can run *C-u 2 M-x eshell*
to create a eshell numbered 2. If eshell 2 already exists, you will switch to
it. If *M-x* is bound to *helm-M-x*, run *M-x C-u 2 eshell* instead.

** Term
   
Use =multi-term= to handle multiple terms. Use *\-mn* to create new term or
switch to anther existing term.

You can key in command in char mode and copy/paste in line mode. The follow
function and kbd provide easy toggling.
#+BEGIN_SRC emacs-lisp
(defun my-toggle-term-line-char-mode ()
  "Toggle term between line mode and char mode"
  (interactive)
  (if (term-in-line-mode)
      (term-char-mode)
    (term-line-mode)))
;; use key alist defined in multi-term.el to define key
(add-to-list 'term-bind-key-alist
             '("C-c C-j" . my-toggle-term-line-char-mode))
(add-to-list 'term-bind-key-alist
             '("C-c C-k" . my-toggle-term-line-char-mode))
#+END_SRC
