#+TITLE: Starter Kit Term
#+OPTIONS: toc:nil num:nil ^:nil

This is part of the [[file:starter-kit.org][Emacs Starter Kit]].

* Starter Kit Term
  
** Eshell
[[http://www.emacswiki.org/emacs/CategoryEshell][Eshell]] is a great shell.

*** Configurations

#+begin_src emacs-lisp
  (setq eshell-cmpl-cycle-completions nil
        eshell-save-history-on-exit t
        eshell-cmpl-dir-ignore "\\`\\(\\.\\.?\\|CVS\\|\\.svn\\|\\.git\\)/\\'")
  
  (eval-after-load 'esh-opt
    '(progn
       ;; TODO: for some reason requiring this here breaks it, but
       ;; requiring it after an eshell session is started works fine.
       ;; (require 'eshell-vc)
       (setenv "PAGER" "cat")
       ; (set-face-attribute 'eshell-prompt nil :foreground "turquoise1")
       (add-hook 'eshell-mode-hook ;; for some reason this needs to be a hook
                 '(lambda () (define-key eshell-mode-map "\C-a" 'eshell-bol)))
       (add-hook 'eshell-mode-hook 'turn-on-eldoc-mode)
       (add-to-list 'eshell-visual-commands "ssh")
       (add-to-list 'eshell-visual-commands "tail")
       (add-to-list 'eshell-command-completions-alist
                    '("gunzip" "gz\\'"))
       (add-to-list 'eshell-command-completions-alist
                    '("tar" "\\(\\.tar|\\.tgz\\|\\.tar\\.gz\\)\\'"))
       ;; (add-to-list 'eshell-output-filter-functions 'eshell-handle-ansi-color)
       ))
#+end_src

The =eshell= directory holds alias definitions and history
information.  It is much like a =.bashrc= file for those who are
familiar with bash.  This set the value of =eshell-directory-name= to
point to the =eshell= directory in this directory.  The =alias= file
is pre-populated with some generally applicable aliases.

#+begin_src emacs-lisp
  (setq eshell-directory-name
        (expand-file-name "./" (expand-file-name "eshell" starter-kit-dir)))
#+end_src

*** Multiple eshells
You can create eshell by just *M-x eshell*, or if can run *C-u 2 M-x eshell*
to create a eshell numbered 2. If eshell 2 already exists, you will switch to
it. If *M-x* is bound to *helm-M-x*, run *M-x C-u 2 eshell* instead.

** Term
   
*** Multi eshell

Use =multi-eshell= to handle multiple shells. Use *\-mn* to create new shell or
switch to anther existing shell. Shell doesn't support zsh well, so specify
shell file name to be bash.
#+begin_src emacs-lisp
(setq explicit-shell-file-name "/usr/bin/bash")
(setq explicit-bash-args '("--noediting" "--login" "-i"))
#+end_src

*** Term and ansi-term
    
In most cases, shell is in my favour. Only when I want to run another app
inside emacs, I will resort to to awkward term or ansi-term.

You can key in command in char mode and copy/paste in line mode. The follow
function and kbd provide easy toggling.

#+BEGIN_SRC emacs-lisp
(defun my-toggle-term-line-char-mode ()
  "Toggle term between line mode and char mode"
  (interactive)
  (if (term-in-line-mode)
      (progn
        (message "Switch to char mode!")
        (term-char-mode))
    (progn
      (message "Switch to line mode")
      (term-line-mode))))

(add-hook 'term-mode-hook
          (lambda ()
            (define-key term-mode-map (kbd "C-c C-j") 'my-toggle-term-line-char-mode)
            (define-key term-raw-map (kbd "C-c C-j") 'my-toggle-term-line-char-mode)))
#+END_SRC
