#+TITLE: Starter Kit Python
#+OPTIONS: toc:nil num:nil ^:nil

This is part of the [[file:starter-kit.org][Emacs Starter Kit]].

* Starter kit Python

Support for the Python programming language.

** Completion
Never used rope, ropemacs, pymacs ... They are ugly too slow. The newly
emerging [[https://github.com/davidhalter/jedi][jedi]] is a better choice, though it is almost impossible to install
manually. Or you can just enable company mode or auto-complete instead of
setup jedi.

To install jedi manually:
#+BEGIN_SRC sh
  pip install jedi
  pip install epc
#+END_SRC

To use my configuration, set JEDI_SERVER environment to be
/path/to/jediepcserver.py.
#+BEGIN_SRC emacs-lisp
(defun my-jedi-conf ()
  (jedi:setup)
  (setq jedi:setup-keys t)
  (setq jedi:complete-on-dot t))

(defun my-jedi-setup ()
  (interactive)
  (if (file-directory-p "~/.emacs.d/.python-environments")
      (my-jedi-conf)
    (if (getenv "JEDI_SERVER")
        (progn (setq jedi:server-command
                     `(,(executable-find "python") ,(getenv "JEDI_SERVER")))
               (my-jedi-conf))
      (if (executable-find "jediepcserver.py")
          (progn
            (setq jedi:server-command
                  `(,(executable-find "jediepcserver.py")))
            (my-jedi-conf))))))
#+END_SRC

** Configuration for python mode
Flyspell is used to check spelling in comment; outline mode is used to fold
code blocks, which is realised by defining key words like *def*, *class* and
so on and you can add your own key words.
#+BEGIN_SRC emacs-lisp
(defun my-python-conf ()
  (make-local-variable 'outline-regexp)
  (setq outline-regexp " *\\(def \\|class \\|if __name__\\)")
  (my-jedi-setup)
  ;; (highlight-indentation-mode)
  (highlight-indentation-current-column-mode))
(add-hook 'python-mode-hook 'my-python-conf)
#+END_SRC

** Use Cython mode
   :PROPERTIES:
   :CUSTOM_ID: cython
   :END:
#+begin_src emacs-lisp
    (add-to-list 'auto-mode-alist '("\\.pyx\\'" . cython-mode))
    (add-to-list 'auto-mode-alist '("\\.pxd\\'" . cython-mode))
    (add-to-list 'auto-mode-alist '("\\.pxi\\'" . cython-mode))
#+end_src

** Set up for Sconstruct
[[http://www.scons.org/][SCons]] is a software construction tool written in python. The /input card/ or
/script/ for SCons is *SConstruct*, which can be treated as Python script.
#+BEGIN_SRC emacs-lisp
(setq auto-mode-alist
      (append '(("SConstruct\\'" . python-mode)
		("SConscript\\'" . python-mode))
              auto-mode-alist))
#+END_SRC

** IPython set up
   
Activate IPython in ansi-term.
#+BEGIN_SRC emacs-lisp
(defun my-ipython ()
  "Activate IPython shell"
  (interactive)
  ;; Get buffer index
  (setq my-ipython-shell-index 0)
  (while (get-buffer (format "*IPython <%d>*" my-ipython-shell-index))
    (setq my-ipython-shell-index (+ 1 my-ipython-shell-index)))
  ;; Create new ansi term
  (ansi-term "ipython" (format "IPython <%d>" my-ipython-shell-index))
  (switch-to-buffer (format "*IPython <%d>*" my-ipython-shell-index)))
#+END_SRC

Or you can use *M-x C-u run-python* command to run Python interpreter. Here
*C-u* prefix enables you input the Python interpreter such IPython.
** Run Windows Python interpreter in Cygwin platform
Don't do this. You will fall into a pit. If you have to, there are several
ways:
- You are under directory where script to run exists ::
  #+BEGIN_SRC sh
    /path/to/windows/python script.py [args]
  #+END_SRC
  
- You are not there ::
     #+BEGIN_SRC sh
     cat /path/to/script.py | /path/to/windows/python - [args]
     #+END_SRC
     =-= means python interpreter will read from stdin. Note that you can't do
     this in eshell for that eshell can't handle stdin redirection.
  
- You are editing the script ::
     Make a symbolic to Windows Python:
     #+BEGIN_SRC sh
     ln -s /path/to/windows/python ~/bin/winpy
     #+END_SRC
     Then define quickrun like [[~/.emacs.d/starter-kit-quickrun.org][this]]. Finally run quickrun.
     
- You are in dired ::
     Run *M-x dired-open-w32-prog-at-point* or *C-u M-x
     dired-open-w32-prog-at-point* as defined [[~/.emacs.d/starter-kit-dired.org][here]].

There is no perfect way. The first and second are tricky to handle the
path. The quickrun will be confused by *#!/usr/bin/env python* and have no
idea whether to run winpy or python. The path problems also exist for
quickrun. The dired way is perfect only if you don't use
matplotlib. Matplotlib can not create configuration directory for some reason.
