#+TITLE: Starter Kit LaTeX
#+OPTIONS: toc:nil num:nil ^:nil

* Starter Kit LaTeX
** Install latex
   :PROPERTIES:
   :TANGLE:   no
   :END:

First install the latest *texlive*. Then install *auctex*:
#+begin_src sh
cd ~/.emacs.d/auctex-11.88/
./configure --with-lispdir=path/to/site-lisp
make
make install
#+end_src

** cdlatex
   :PROPERTIES:
   :TANGLE:   no
   :END:

To combine yasnippet with cdlatex:
#+begin_src emacs-lisp
(defun tab-yas-or-cdlatex ()
  (interactive)
  (let* ((bounds (bounds-of-thing-at-point 'word))
         (b0 (car bounds))
         (b1 (cdr bounds))
         (p (point))
         (yas-fallback-behavior 'return-nil))
    (cond
     ((and yas-minor-mode
           b0
           b1
           (<= (- p b0) 3)
           (= p b1)
           (yas-expand)))
     ((and yas-minor-mode
           (yas--snippets-at-point))
      (when (and (looking-back " ")
                 (looking-at "[\]})\n\[({, ]"))
        (delete-region (1- p) p))
      (yas-next-field))
     (t
      (call-interactively 'cdlatex-tab)))))
#+end_src

I use *yasnippet* to expand math command, latex environments, ... So
[[help:cdlatex-command-alist-default][cdlatex-command-alist-default]] is of no use. The cdlatex-style of inserting
math symbols with prefix =`= and ='= is very strange and disturbing. I use
[[help:helm-insert-latex-math][helm-insert-latex-math]] instead.
#+begin_src emacs-lisp
(with-eval-after-load 'cdlatex
  (setq cdlatex-command-alist-comb nil)
  (define-key cdlatex-mode-map
    (cdlatex-get-kbd-vector cdlatex-math-symbol-prefix)
    'self-insert-command)
  (define-key cdlatex-mode-map "\t" 'tab-yas-or-cdlatex)
  (define-key cdlatex-mode-map
    (cdlatex-get-kbd-vector cdlatex-math-modify-prefix)
    'self-insert-command))
#+end_src

*tesmathp* which is bundled with *auctex* is needed by *cdlatex*. However,
*auctex* is not that easy to install. So I take *texmathp* alone from *auctex*
*and add it to my load path [[file:src/texmathp/][file:~/.emacs.d/src/texmathp/]].

** Customary Customization

#+BEGIN_QUOTE
To edit LaTeX documents, you will probably want to include the following in
your ~/.emacs.
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
(when auctex-root
  (load "auctex" t)
  (load "preview-latex" t))

(when auctex-root
  (add-to-list 'auto-mode-alist '("\\.tex\\'" . TeX-latex-mode)))

(setq Tex-auto-save t)
(setq Tex-parse-self t)
#+END_SRC

** PDF preview

To use Evince for PDF preview, you should activate PDF mode. To activate
inverse search, activate ... mode, though the author never succeed.

*Notes* that:
+ Just *C-c C-c*, *View* and finally *Evince* to preview.
+ The forward search is enabled by locating the page index of PDF file.
+ Evince is activated in full screen, *M-space* to show tool bar and *M-<F4>*
  to close in Windows.

#+BEGIN_SRC emacs-lisp
(setq TeX-PDF-mode t)
(when auctex-root
  (add-hook 'LaTeX-mode-hook 'TeX-source-correlate-mode))
(setq TeX-source-correlate-start-server t)
(setq TeX-view-program-list '(("Evince" "evince -f -i %(outpage) %o")))
(setq TeX-view-program-selection '((output-pdf "Evince")))
#+END_SRC

** Other minor mode

XeLaTeX prevails over other LaTeX compilers for that it could use system
fonts, which is very convenient for languages such as *Chinese*. To enable
source highlight packages such as [[http://www.minted.com/][minted]] and [[http://www.ctan.org/pkg/listings][listings]] *-shell-escape* should
be added to compilation command. To enable inverse search (in theory it
works), add *-syntex=1*. To make compilation do not stop when meeting errors,
add *-interaction=nonstopmode*. You may also want to spread a document over
multiple files and wish AuCTeX compile the master file even the current buffer
is not the master. This is recognized by setting *TeX-master* variable to be
the master file and setting *TeX-master* as the input file of XeLaTeX command
within TeX-command-list.

To compile TeX file, just key in *C-c C-c* and select *XeLaTeX*.

#+BEGIN_SRC emacs-lisp
(defun my-latex-config ()
  (setq-default TeX-master t)
  (add-to-list
   'TeX-command-list
   '("XeLaTeX" "%`xelatex -shell-escape -synctex=1 %(mode)%'  %t"
     TeX-run-TeX nil TeX-master))
  (setq LaTeX-command-style
        '(("" "%(PDF)%(latex) %(extraopts) -shell-escape %S%(PDFout)")))
  (setq TeX-command-default "LaTex")
  (setq TeX-save-query nil)
  (setq TeX-show-compilation t)
  (turn-on-flyspell)
  ;; (LaTeX-math-mode)
  (reftex-mode)
  (linum-mode 1)
  (setq TeX-newline-function 'newline-and-indent)
  ;; (cdlatex-mode)
  (TeX-fold-mode))
(when auctex-root
  (add-hook 'LaTeX-mode-hook 'my-latex-config))
#+END_SRC

** RefTeX

#+BEGIN_QUOTE
RefTEX is a specialized package for support of labels, references, citations,
and the indices in LATEX. RefTEX wraps itself round four LATEX macros: \label,
\ref, \cite, and \index. Using these macros usually requires looking up
different parts of the document and searching through BibTEX database
files. RefTEX automates these time-consuming tasks almost entirely. It also
provides functions to display the structure of a document and to move around
in this structure quickly.
#+END_QUOTE

*Note* that the default bib file is fixed and he who use it should modify the
 path.

#+BEGIN_SRC emacs-lisp
(setq reftex-plug-into-AUCTeX t)
(setq reftex-default-bibliography
      (quote
       ("~/share/bib/My_Collection.bib")))
#+END_SRC
