#+TITLE: Starter Kit Emacs
#+OPTIONS: toc:nil num:nil ^:nil

* Starter Kit Emacs

** Font size
#+BEGIN_SRC emacs-lisp
(set-face-attribute 'default (selected-frame) :height 120)
#+END_SRC
   
** Font for English and Chinese
  
The author use emacs by "emacs -nw" and let the terminal handle the fonts. Or
the English font will be Consolas and Chinese font be Microsoft Yahei.

#+BEGIN_SRC emacs-lisp
(when (not *terminal*)
  (progn
    (set-face-attribute
     'default nil :font "Consolas")
    (dolist (charset '(kana han symbol cjk-misc bopomofo))
      (set-fontset-font (frame-parameter nil 'font)
                        charset
                        (font-spec :family "Microsoft Yahei" :size 14)))
    )
  )
#+END_SRC

** Emacs Layout
The toolbar and scroll bar are too ugly and disable it.
#+BEGIN_SRC emacs-lisp
(scroll-bar-mode 0)
(column-number-mode 1)
#+END_SRC

It's not easy to recognise the completion words in horizontally split window
if two windows are already split horizontally. Therefore set Emacs to split
vertically by default.
#+BEGIN_SRC emacs-lisp
(setq split-height-threshold nil)
(setq split-width-threshold 160)
#+END_SRC

** Line number

Use relative line number. Set linum-relative-current-symbol to be empty string
so that linum-relative will show the real line number at current line.
#+BEGIN_SRC emacs-lisp
(require 'linum-relative)
(setq linum-relative-current-symbol "")
#+END_SRC


** 80 Column Rule
It's a good habit to obey to 80 column rule. In the convenience of adding
continuation marker in code such as Fortran, two columns are spared.
#+BEGIN_SRC emacs-lisp
(setq default-fill-column 78)
#+END_SRC

** Disable recentering
For smooth scrolling and disabling the auto-recentering of emacs screen when
moving cursor. Set scroll margin to be 4 so that an ape can see the following
lines of codes.
#+BEGIN_SRC emacs-lisp
(setq scroll-step 1
      scroll-conservatively 10000
      auto-window-vscroll nil)
(setq scroll-margin 4)
#+END_SRC

