#+TITLE: Starter Kit Dired
#+OPTIONS: toc:nil num:nil ^:nil

* Starter Kit Dired

** Basic settings

#+BEGIN_SRC emacs-lisp
(eval-after-load "dired-aux"
  '(require 'dired-async))
;; try to guess destination
(setq dired-dwim-target t)
;; use the same buffer for viewing dir, instead of spawning many
(put 'dired-find-alternate-file 'disabled nil)
(eval-after-load "dired"
  `(progn
     (define-key dired-mode-map (kbd "RET") 'dired-find-alternate-file)
     (define-key dired-mode-map (kbd "^") #'(lambda ()
                                              (interactive)
                                              (find-alternate-file "..")))
     (define-key dired-mode-map (kbd "<f5>") 'dired-hide-details-mode)))
#+END_SRC

** How dired presents
#+BEGIN_SRC emacs-lisp
(setq dired-listing-switches "-lAh1v --group-directories-first")
(eval-after-load "dired"
  `(progn
     (require 'dired+)
     ;; Emacs 24.4+
     (when (fboundp 'dired-hide-details-mode)
       (global-dired-hide-details-mode t))))
#+END_SRC

- l: Is the only mandatory one.
- A: Means to list all files but . and ...
- G: Don't show group information. These days, when there are more laptops
  than people, the group info is rarely useful.
- h: Human readable sizes, such as M for mebibytes.
- 1v: Affects the sorting of digits, hopefully in a positive way.
- --group-directories-first: self-explanatory, I like to have the directories
  on the top, separate from the files.

** Find name dired

+ Use [[elisp:find-name-dired]] instead of [[elisp:find-dired]] for the former's
  simplicity.
+ By default Emacs will pass *-exec* to find and that makes it very slow. It is
  better to collate the matches and then use *xargs* to run the command. To do
  this instead add this to your =~/.emacs=:
#+begin_src emacs-lisp
(setq find-ls-option '("-print0 | xargs -0 ls -ld" . "-ld"))
#+end_src

** Tips
*** key bindings
- *w* copies file name to ring. *C-u 0 w* copies full path.
- *!* run shell command, *&* run shell command synchronously.
