#+TITLE: Starter Kit Theme
#+OPTIONS: toc:nil num:nil ^:nil

* Starter Kit Theme
  
** Emacs Layout
The toolbar and scroll bar are too ugly and disable it.
#+BEGIN_SRC emacs-lisp
(scroll-bar-mode 0)
(column-number-mode 1)
#+END_SRC

It's not easy to recognise the completion words in horizontally split window
if two windows are already split horizontally. Therefore set Emacs to split
vertically by default.
#+BEGIN_SRC emacs-lisp
(setq split-height-threshold nil)
(setq split-width-threshold 160)
#+END_SRC
  
** Font size
#+begin_src emacs-lisp
(set-face-attribute 'default (selected-frame) :height 120)
#+end_src

** Font for English and Chinese
  
The author use emacs by "emacs -nw" and let the terminal handle the fonts. Or
the English font will be Consolas and Chinese font be Microsoft Yahei.

#+BEGIN_SRC emacs-lisp
(when (and
       (not *terminal*)
       (or *win32* *cygwin*))
  (progn
    (set-face-attribute
     'default nil :font "Consolas")
    (dolist (charset '(kana han symbol cjk-misc bopomofo))
      (set-fontset-font (frame-parameter nil 'font)
                        charset
                        (font-spec :family "Microsoft Yahei" :size 14)))))
#+END_SRC

** Fringe
   
Don't show fringe in GUI, it's too ugly.
#+BEGIN_SRC emacs-lisp 
(fringe-mode 0)
#+END_SRC

** Old
   :PROPERTIES:
   :tangle: no
   :END:

Emacs24 has build in support for saving and loading themes.

A Theme builder is available at http://elpa.gnu.org/themes/ along with
a list of pre-built themes at http://elpa.gnu.org/themes/view.html and
themes are available through ELPA.

Downloaded themes may be saved to the =themes/= directory in the base
of the starter kit which ignored by git.  Once downloaded and
evaluated a theme is activated using the =load-theme= function.

#+BEGIN_SRC emacs-lisp
(color-theme-initialize)
(if (or *terminal* (string= "light" (getenv "EMACS_COLOR_THEME")))
    (progn (color-theme-solarized-light)
           (set-face-background 'highlight-indentation-face "#073642")
           (set-face-background 'highlight-indentation-current-column-face "#eee8d5"))
  (progn (color-theme-solarized-dark)
         (set-face-background 'highlight-indentation-face "#073642")
         (set-face-background 'highlight-indentation-current-column-face "#073642")))
#+END_SRC
   
Load powerline after color theme is set. If you change the color theme in
running emacs, the expressions as follows should be re-evaluated.
#+BEGIN_SRC emacs-lisp 
(require 'powerline)
(set-face-attribute 'mode-line nil
                    :background "dim gray"
                    :foreground "cyan"
                    :inverse-video nil
                    :box nil
                    :underline nil)
(set-face-attribute 'mode-line-inactive nil
                    :background "dim gray"
                    :foreground "light gray"
                    :inverse-video nil
                    :box nil
                    :underline nil)
#+END_SRC

** Power line
   
My powerline theme based on powerline-default-theme.
#+begin_src emacs-lisp
(defun powerline-my-theme ()
  "Setup my mode-line."
  (interactive)
  (setq-default mode-line-format
                '("%e"
                  (:eval
                   (let* ((active (powerline-selected-window-active))
                          (mode-line (if active 'mode-line 'mode-line-inactive))
                          (face2 (if active 'powerline-active1 'powerline-inactive1))
                          (face1 (if active 'powerline-active2 'powerline-inactive2))
                          (separator-left (intern (format "powerline-%s-%s"
                                                          powerline-default-separator
                                                          (car powerline-default-separator-dir))))
                          (separator-right (intern (format "powerline-%s-%s"
                                                           powerline-default-separator
                                                           (cdr powerline-default-separator-dir))))
                          (lhs (list (powerline-raw "%*" face2 'l)
                                     (powerline-buffer-size face2 'l)
                                     (powerline-raw mode-line-mule-info face2 'l)
                                     (powerline-buffer-id face2 'l)
                                     (when (and (boundp 'which-func-mode) which-func-mode)
                                       (powerline-raw which-func-format face2 'l))
                                     (powerline-raw " " face2)
                                     (funcall separator-left face2 face1)
                                     (when (boundp 'erc-modified-channels-object)
                                       (powerline-raw erc-modified-channels-object face1 'l))
                                     (powerline-major-mode face1 'l)
                                     (powerline-process face1)
                                     (powerline-minor-modes face1 'l)
                                     (powerline-narrow face1 'l)
                                     (powerline-raw " " face1)
                                     (funcall separator-left face1 face2)
                                     (powerline-vc face2 'r)))
                          (rhs (list (powerline-raw global-mode-string face2 'r)
                                     (funcall separator-right face2 face1)
                                     (powerline-raw "%4l" face1 'l)
                                     (powerline-raw ":" face1 'l)
                                     (powerline-raw "%3c" face1 'r)
                                     (funcall separator-right face1 face2)
                                     (powerline-raw " " face2)
                                     (powerline-raw "%6p" face2 'r))))
                     (concat (powerline-render lhs)
                             (powerline-fill face2 (powerline-width rhs))
                             (powerline-render rhs)))))))
#+end_src

** New
   
[[https://github.com/bbatsov/solarized-emacs][Solarized theme here]] seems better than [[https://github.com/sellout/emacs-color-theme-solarized][this one]].
#+begin_src emacs-lisp
(defadvice load-theme (around starter-kit-load-theme disable)
  ad-do-it
  (set-face-attribute 'mode-line nil
                      :foreground "cyan"
                      :inverse-video nil)
  (set-face-attribute 'mode-line-inactive nil
                      :inverse-video nil)
  (require 'powerline)
  (powerline-my-theme))

(defun starter-kit-solarized-emacs-setup ()
  ;; make the fringe stand out from the background
  (setq solarized-distinct-fringe-background t)
  ;; make the modeline high contrast
  (setq solarized-high-contrast-mode-line t)
  ;; Use less bolding
  (setq solarized-use-less-bold t)
  ;; Use more italics
  (setq solarized-use-more-italic t)
  ;; Use less colors for indicators such as git:gutter, flycheck and similar.
  (setq solarized-emphasize-indicators nil)

  (ad-enable-advice 'load-theme 'around 'starter-kit-load-theme)
  (ad-activate 'load-theme)

  (load-theme 'solarized-dark t))

(starter-kit-solarized-emacs-setup)
#+end_src
