#+TITLE: Starter Kit Emacs
#+OPTIONS: toc:nil num:nil ^:nil

* Starter Kit Emacs

** Encoding system
This configures layout, encoding and odds and ends of Emacs. To begin with set
the encoding to be utf-8.
#+BEGIN_SRC emacs-lisp
(setq locale-coding-system 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(prefer-coding-system 'utf-8)
#+END_SRC

** Font for English and Chinese
Then set the fonts of Emacs for English and Chinese respectively. *Consolas*
is a good choice for coder and *Microsoft Yahei* favours your eyes for
long-time reading. You should note that not all of the systems has *Microsoft
Yahei*, so you may download from Net and install it. To ensure that width of
one Chinese words equals two English words, you should set the size to be
*14*. If you are not accustomed to the size, type *C-x C-+* to increase scale
or *C-x C--* to decrease.
#+BEGIN_SRC emacs-lisp
(set-face-attribute
 'default nil :font "Consolas")
(dolist (charset '(kana han symbol cjk-misc bopomofo))
  (set-fontset-font (frame-parameter nil 'font)
                    charset
                    (font-spec :family "Microsoft Yahei" :size 14)))
#+END_SRC

** Emacs Layout
The toolbar and scroll bar are too ugly and disable it.
#+BEGIN_SRC emacs-lisp
(scroll-bar-mode 0)
(column-number-mode 1)
#+END_SRC

It's not easy to recognise the completion words in horizontally split window
if two windows are already split horizontally. Therefore set Emacs to split
vertically by default.
#+BEGIN_SRC emacs-lisp
(setq split-height-threshold nil)
(setq split-width-threshold 160)
#+END_SRC

** 80 Column Rule
It's a good habit to obey to 80 column rule. In the convenience of adding
continuation marker in code such as Fortran, two columns are spared.
#+BEGIN_SRC emacs-lisp
(setq default-fill-column 78)
#+END_SRC

